# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Zhao
email: john.xinuo.zhao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  John Zhao's Website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xinuozhao.info/" # the base hostname & protocol for your site
github_username: johnxzhao
qq_number: 330748330
exclude: ['README.md']

# Build settings
markdown: kramdown
